### PR TITLE
Add `dependabot.yml`

### PR DESCRIPTION
**Pull request by gomzyakov**
## Added

- `dependabot.yml` to implement automatic dependency updating

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by jetexe** [comment]
Hey! What about switching to renovate instead of depandabot?

**Comment by gomzyakov** [comment]
> Hey! What about switching to renovate instead of depandabot?
> It allows you to update all types of deps (even #23 can be handled with it's help)

@jetexe Hello Pasha!

We will discuss this with the @eldario 

I successfully set up Renovate (following [this](https://github.com/renovatebot/tutorial) tutorial) on one of my hobby project, and it's really easy!

**Comment by jetexe** [comment]
That tutor not covers one of the most poverfull feature of `renovate`: regex managers!

You can add this into config file:
```json
{
"regexManagers": [
    {
      "description": "Custom renovations",
      "fileMatch": [
        "(^|/|\\.)Dockerfile$",
        "(^|/)Dockerfile\\.[^/]*$",
        "\\.ya?ml$",
        "\\.b?a?sh",
        "(^|/|\\.)Makefile"
      ],
      "matchStrings": [
        "# renovate: source=(?<datasource>\\S+) name=(?<depName>\\S+)(?: depType=(?<depType>[a-z-]+?))?(?: versioning=(?<versioning>\\S+))?(?: extractVersion=(?<extractVersion>\\S+))?[^\\n]*\\n[^\\n]+[:=]['\"\\s]*(?<currentValue>[^\"'\\n\\s]+)[\"']?[^\\n]*\\n?"
      ],
      "datasourceTemplate": "{{#if datasource}}{{{datasource}}}{{else}}github-releases{{/if}}",
      "depNameTemplate": "{{depName}}",
      "extractVersionTemplate": "{{#if extractVersion}}{{{extractVersion}}}{{else}}^v?(?<version>.+)${{/if}}",
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}",
      "depTypeTemplate": "{{#if depType}}{{depType}}{{else}}libraries{{/if}}"
    }
  ],
}
 ```

And then just add a comment into `Dockerfile` under versioned variable:
```
# renovate: source=github-tags name=xdebug/xdebug versioning=semver
ENV XDEBUG_VERSION="3.0"
```

And it will update it!

**Comment by gomzyakov** [comment]
PR is no longer relevant. We looked towards Renovate.

Thanks @jetexe !

**Pull request closed without merging**
